### ISSUE TITLE
Прошу проверить

### ISSUE THREAD

**Issue by zakiryanova-java** [zakiryanova-java/InMemory-JdbcImpl#1]
@coursar, прошу проверить, а также подсказать по вопросу FIXME
`public List <House> getByDistrict(String district) {
        return getByDistrict(district).stream().filter(o -> o.getDistrict().equals(district)).collect(Collectors.toList());
        //FIXME: как выкинуть DistrictNotFoundException?
    }`

**Comment by coursar** [comment]
Для того, чтобы так делать, вам нужно заранее знать список районов (вы же его не знаете), поэтому в данном случае это ноправдано.
