### ISSUE TITLE
Имена house, house2 - плохие имена

### ISSUE THREAD

**Issue by coursar** [zakiryanova-java/InMemory-JdbcImpl#3]
https://github.com/zakiryanova-java/InMemory-JdbcImpl/blob/b1688c796b00ed8dde2d5b34e5e7b4d72c3f9fcb/src/main/java/ru/itpark/Main.java#L11-L12

**Comment by zakiryanova-java** [comment]
https://github.com/zakiryanova-java/InMemory-JdbcImpl/blob/c7840c680be490ae11aa4758b1e4b44b053e7c4f/src/main/java/ru/itpark/Main.java#L10-L12
